debug: true

server:
  port: 80
spring:
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  jpa:
    hibernate:
      ddl-auto: validate
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://222.197.166.34:3306/vivedu_ckd?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: DoDo1306!
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy.MM.dd HH:mm
    time-zone: "GMT+8"
  servlet:
    multipart:
      max-request-size: 4194304
      max-file-size: 4194304
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.vivedu.ckd.dao
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.vivedu.ckd.dao: debug
redis:
  host: 127.0.0.1
  port: 6379

